interface GeneralList {
  package: string;
  model_number: string;
  secondary_material: string;
  configuration: string;
  upholstery_material: string;
  upholstery_color: string;
}

export const generalInformation: GeneralList[] = [
  {
    package: "1 sectional sofa",
    model_number: "TFCBLIGRBL6SRHS",
    secondary_material: "Solid Wood",
    configuration: "L-shaped",
    upholstery_material: "Fabric + Cotton",
    upholstery_color: "Bright Grey & Lion",
  },
  {
    package: "2 sectional sofas",
    model_number: "TFCBLIGRBL6SRHT",
    secondary_material: "Engineered Wood",
    configuration: "U-shaped",
    upholstery_material: "Leather",
    upholstery_color: "Dark Grey & Brown",
  },
  {
    package: "3 sectional sofas",
    model_number: "TFCLUXBLGR4UQ",
    secondary_material: "Steel",
    configuration: "Square-shaped",
    upholstery_material: "Polyester",
    upholstery_color: "Beige & Dark Brown",
  },
  {
    package: "4 sectional sofas",
    model_number: "XLSRCGRBL9RFT",
    secondary_material: "Aluminum",
    configuration: "S-shaped",
    upholstery_material: "Wool",
    upholstery_color: "Light Blue & Grey",
  },
  {
    package: "5 sectional sofas",
    model_number: "KMGRTYFTG39P",
    secondary_material: "Plastic",
    configuration: "Circular",
    upholstery_material: "Microfiber",
    upholstery_color: "Green & Black",
  },
  {
    package: "6 sectional sofas",
    model_number: "PLXTYGRSUT8D",
    secondary_material: "Glass",
    configuration: "Hexagonal",
    upholstery_material: "Velvet",
    upholstery_color: "Orange & Blue",
  },
  {
    package: "7 sectional sofas",
    model_number: "FFFGGRRSTT5P",
    secondary_material: "Carbon Fiber",
    configuration: "T-shaped",
    upholstery_material: "Silk",
    upholstery_color: "Purple & White",
  },
  {
    package: "8 sectional sofas",
    model_number: "TRXYGR8BLKSP",
    secondary_material: "Rubber",
    configuration: "Octagonal",
    upholstery_material: "Suede",
    upholstery_color: "Brown & Olive",
  },
  {
    package: "9 sectional sofas",
    model_number: "LPGGRFR9TYUJ",
    secondary_material: "Iron",
    configuration: "Rectangular",
    upholstery_material: "Chenille",
    upholstery_color: "White & Gold",
  },
  {
    package: "10 sectional sofas",
    model_number: "TGFBLQNGT7YH",
    secondary_material: "Brass",
    configuration: "Pentagonal",
    upholstery_material: "Linen",
    upholstery_color: "Pink & Silver",
  },
  {
    package: "11 sectional sofas",
    model_number: "GRYSPCKL45TY",
    secondary_material: "Copper",
    configuration: "U-shaped",
    upholstery_material: "Nylon",
    upholstery_color: "Teal & Black",
  },
  {
    package: "12 sectional sofas",
    model_number: "KPLMRSF12MNT",
    secondary_material: "Bamboo",
    configuration: "Oval-shaped",
    upholstery_material: "Lace",
    upholstery_color: "Magenta & Cyan",
  },
  {
    package: "13 sectional sofas",
    model_number: "LMXTY34PNRT",
    secondary_material: "Recycled Wood",
    configuration: "Trapezoidal",
    upholstery_material: "Canvas",
    upholstery_color: "Red & Cream",
  },
  {
    package: "14 sectional sofas",
    model_number: "GGSPCKFXW90D",
    secondary_material: "Pine",
    configuration: "Y-shaped",
    upholstery_material: "Denim",
    upholstery_color: "Navy & White",
  },
  {
    package: "15 sectional sofas",
    model_number: "SKYWNDPK901B",
    secondary_material: "Titanium",
    configuration: "V-shaped",
    upholstery_material: "Cotton",
    upholstery_color: "Sky Blue & Beige",
  },
  {
    package: "16 sectional sofas",
    model_number: "ZNCMNHRVRQ23",
    secondary_material: "Graphene",
    configuration: "O-shaped",
    upholstery_material: "Silicone",
    upholstery_color: "Charcoal & Orange",
  },
  {
    package: "17 sectional sofas",
    model_number: "NPSKGRWRT68J",
    secondary_material: "Teak",
    configuration: "Triangular",
    upholstery_material: "Acrylic",
    upholstery_color: "Yellow & Grey",
  },
  {
    package: "18 sectional sofas",
    model_number: "WRBTCLQWRT45",
    secondary_material: "Rattan",
    configuration: "X-shaped",
    upholstery_material: "Synthetic Leather",
    upholstery_color: "Burgundy & Cream",
  },
  {
    package: "19 sectional sofas",
    model_number: "PLXCDWGR8KLS",
    secondary_material: "Bronze",
    configuration: "Parallel",
    upholstery_material: "Mesh",
    upholstery_color: "Ivory & Maroon",
  },
  {
    package: "20 sectional sofas",
    model_number: "CTGRYLUV123P",
    secondary_material: "Concrete",
    configuration: "Diamond-shaped",
    upholstery_material: "Tweed",
    upholstery_color: "Gold & Navy",
  },
  {
    package: "21 sectional sofas",
    model_number: "PXTSOFA9098P",
    secondary_material: "Maple Wood",
    configuration: "Semi-circular",
    upholstery_material: "Faux Fur",
    upholstery_color: "Turquoise & White",
  },
  {
    package: "22 sectional sofas",
    model_number: "LMBWLTYX123Q",
    secondary_material: "Zinc",
    configuration: "Horseshoe-shaped",
    upholstery_material: "Chiffon",
    upholstery_color: "Lavender & Rose Gold",
  },
  {
    package: "23 sectional sofas",
    model_number: "BRLGNTSP99XT",
    secondary_material: "Acrylic Glass",
    configuration: "Ladder-shaped",
    upholstery_material: "Spandex",
    upholstery_color: "Emerald & Silver",
  },
  {
    package: "24 sectional sofas",
    model_number: "KXPLWMRG7NRT",
    secondary_material: "Ash Wood",
    configuration: "Chevron-shaped",
    upholstery_material: "Corduroy",
    upholstery_color: "Tan & Orange",
  },
  {
    package: "25 sectional sofas",
    model_number: "RXTPWLSV4PKD",
    secondary_material: "Graphite",
    configuration: "Prism-shaped",
    upholstery_material: "Georgette",
    upholstery_color: "Mint & Peach",
  },
  {
    package: "26 sectional sofas",
    model_number: "ZPLWTRKS7LPQ",
    secondary_material: "Stainless Steel",
    configuration: "Ring-shaped",
    upholstery_material: "Mohair",
    upholstery_color: "Coral & Sea Green",
  },
  {
    package: "27 sectional sofas",
    model_number: "SSPLNTVR83JD",
    secondary_material: "Ceramic",
    configuration: "Egg-shaped",
    upholstery_material: "Neoprene",
    upholstery_color: "Plum & Lime",
  },
  {
    package: "28 sectional sofas",
    model_number: "GFTMRN89XWQJ",
    secondary_material: "Polycarbonate",
    configuration: "Leaf-shaped",
    upholstery_material: "Velveteen",
    upholstery_color: "Dark Green & Rust",
  },
  {
    package: "29 sectional sofas",
    model_number: "WKLSGR85VJTP",
    secondary_material: "Hemp Fiber",
    configuration: "Pyramid-shaped",
    upholstery_material: "Brocade",
    upholstery_color: "Silver & Crimson",
  },
  {
    package: "30 sectional sofas",
    model_number: "MTXCLVRX98PL",
    secondary_material: "Plywood",
    configuration: "C-shaped",
    upholstery_material: "Burlap",
    upholstery_color: "Beige & Indigo",
  },
  {
    package: "31 sectional sofas",
    model_number: "VFTLMTGY84RLP",
    secondary_material: "Polyurethane",
    configuration: "Hourglass-shaped",
    upholstery_material: "Faux Leather",
    upholstery_color: "Steel Blue & Charcoal",
  },
  {
    package: "32 sectional sofas",
    model_number: "JKSPMTV8YUQM",
    secondary_material: "Granite",
    configuration: "Infinity-shaped",
    upholstery_material: "Damask",
    upholstery_color: "Black & Gold",
  },
];
