export const productList = [
  {
    id: 1,
    productImage: "/assets/images/products/syltherine.png",
    name: "Syltherine",
    description: "Stylish cafe chair",
    newPrice: "Rp 2.500.000",
    originalPrice: "Rp 3.500.000",
    isNew: false,
    hasDiscount: true,
    discount: "-30%",
  },
  {
    id: 2,
    productImage: "/assets/images/products/syltherine.png",
    name: "Leviosa",
    description: "Stylish cafe chair",
    newPrice: "",
    originalPrice: "Rp 2.500.000",
    isNew: false,
    hasDiscount: false,
    discount: "",
  },
  {
    id: 3,
    productImage: "/assets/images/products/syltherine.png",
    name: "Lolito",
    description: "Luxury big sofa",
    newPrice: "Rp 7.000.000",
    originalPrice: "Rp 14.000.000",
    isNew: false,
    hasDiscount: true,
    discount: "-50%",
  },
  {
    id: 4,
    productImage: "/assets/images/products/syltherine.png",
    name: "Respira",
    description: "Outdoor bar table and stool",
    newPrice: "",
    originalPrice: "Rp 500.000",
    isNew: true,
    hasDiscount: false,
    discount: "",
  },
  {
    id: 5,
    productImage: "/assets/images/products/syltherine.png",
    name: "Grifo",
    description: "Night lamp",
    newPrice: "",
    originalPrice: "Rp 1.500.000",
    isNew: false,
    hasDiscount: false,
    discount: "",
  },
  {
    id: 6,
    productImage: "/assets/images/products/syltherine.png",
    name: "Muggo",
    description: "Luxury sofa",
    newPrice: "",
    originalPrice: "Rp 150.000",
    isNew: true,
    hasDiscount: false,
    discount: "",
  },
  {
    id: 7,
    productImage: "/assets/images/products/syltherine.png",
    name: "Pingky",
    description: "Luxury big sofa",
    newPrice: "Rp 7.000.000",
    originalPrice: "Rp 14.000.000",
    isNew: false,
    hasDiscount: true,
    discount: "-50%",
  },
  {
    id: 8,
    productImage: "/assets/images/products/syltherine.png",
    name: "Nico",
    description: "Luxury brown leather sofa",
    newPrice: "",
    originalPrice: "Rp 8.500.000",
    isNew: true,
    hasDiscount: false,
    discount: "",
  },
];
