interface ProductInfo {
  filling_material: string;
  finish_type: string;
  headrest: string;
  max_load_capacity: number;
  origin: string;
}

export const productInformation: ProductInfo[] = [
  {
    filling_material: "Foam",
    finish_type: "Bright Grey & Lion",
    headrest: "No",
    max_load_capacity: 280,
    origin: "India",
  },
  {
    filling_material: "Memory Foam",
    finish_type: "Dark Blue & White",
    headrest: "Yes",
    max_load_capacity: 300,
    origin: "USA",
  },
  {
    filling_material: "Polyester Fiber",
    finish_type: "Red & Black",
    headrest: "No",
    max_load_capacity: 250,
    origin: "China",
  },
  {
    filling_material: "Gel Foam",
    finish_type: "Light Grey & Pink",
    headrest: "Yes",
    max_load_capacity: 320,
    origin: "Italy",
  },
  {
    filling_material: "Latex",
    finish_type: "Beige & Green",
    headrest: "Yes",
    max_load_capacity: 350,
    origin: "Germany",
  },
  {
    filling_material: "Cotton",
    finish_type: "Navy Blue & Gold",
    headrest: "No",
    max_load_capacity: 270,
    origin: "Mexico",
  },
  {
    filling_material: "Down Feather",
    finish_type: "Brown & Olive",
    headrest: "Yes",
    max_load_capacity: 400,
    origin: "Canada",
  },
  {
    filling_material: "Hemp Fiber",
    finish_type: "Orange & Black",
    headrest: "No",
    max_load_capacity: 200,
    origin: "India",
  },
  {
    filling_material: "Wool",
    finish_type: "Purple & Silver",
    headrest: "Yes",
    max_load_capacity: 280,
    origin: "New Zealand",
  },
  {
    filling_material: "Sponge",
    finish_type: "Light Blue & Yellow",
    headrest: "No",
    max_load_capacity: 290,
    origin: "Brazil",
  },
  {
    filling_material: "Recycled Materials",
    finish_type: "Turquoise & White",
    headrest: "Yes",
    max_load_capacity: 330,
    origin: "Australia",
  },
  {
    filling_material: "Microfiber",
    finish_type: "Teal & Brown",
    headrest: "No",
    max_load_capacity: 260,
    origin: "Japan",
  },
  {
    filling_material: "Synthetic Fiber",
    finish_type: "Grey & Orange",
    headrest: "Yes",
    max_load_capacity: 310,
    origin: "South Korea",
  },
  {
    filling_material: "Cotton Blend",
    finish_type: "Cream & Black",
    headrest: "No",
    max_load_capacity: 240,
    origin: "Vietnam",
  },
  {
    filling_material: "Bamboo Fiber",
    finish_type: "Pink & Grey",
    headrest: "Yes",
    max_load_capacity: 320,
    origin: "Thailand",
  },
  {
    filling_material: "Silk",
    finish_type: "Gold & Burgundy",
    headrest: "No",
    max_load_capacity: 350,
    origin: "Egypt",
  },
  {
    filling_material: "Polyurethane",
    finish_type: "Dark Grey & Olive",
    headrest: "Yes",
    max_load_capacity: 300,
    origin: "Russia",
  },
  {
    filling_material: "Feather Blend",
    finish_type: "Mauve & White",
    headrest: "No",
    max_load_capacity: 280,
    origin: "Sweden",
  },
  {
    filling_material: "PVC",
    finish_type: "Beige & Turquoise",
    headrest: "Yes",
    max_load_capacity: 290,
    origin: "Philippines",
  },
  {
    filling_material: "Latex Blend",
    finish_type: "Mint & Coral",
    headrest: "No",
    max_load_capacity: 360,
    origin: "Spain",
  },
  {
    filling_material: "Fiberfill",
    finish_type: "Lavender & Gold",
    headrest: "Yes",
    max_load_capacity: 340,
    origin: "Portugal",
  },
  {
    filling_material: "Viscoelastic Foam",
    finish_type: "Ivory & Grey",
    headrest: "No",
    max_load_capacity: 310,
    origin: "Italy",
  },
  {
    filling_material: "Recycled Foam",
    finish_type: "Charcoal & Teal",
    headrest: "Yes",
    max_load_capacity: 330,
    origin: "USA",
  },
  {
    filling_material: "Down Alternative",
    finish_type: "Black & Red",
    headrest: "No",
    max_load_capacity: 250,
    origin: "Canada",
  },
  {
    filling_material: "Wool Blend",
    finish_type: "Dark Green & Cream",
    headrest: "Yes",
    max_load_capacity: 320,
    origin: "Australia",
  },
  {
    filling_material: "Microgel",
    finish_type: "Light Grey & Yellow",
    headrest: "No",
    max_load_capacity: 300,
    origin: "Japan",
  },
  {
    filling_material: "Cotton-Polyester Blend",
    finish_type: "Bright Pink & Navy",
    headrest: "Yes",
    max_load_capacity: 270,
    origin: "India",
  },
  {
    filling_material: "Foam Rubber",
    finish_type: "Olive & White",
    headrest: "No",
    max_load_capacity: 290,
    origin: "Brazil",
  },
  {
    filling_material: "Silicone Foam",
    finish_type: "Coral & Grey",
    headrest: "Yes",
    max_load_capacity: 340,
    origin: "Germany",
  },
  {
    filling_material: "Air Mesh",
    finish_type: "Sea Green & Beige",
    headrest: "No",
    max_load_capacity: 260,
    origin: "South Korea",
  },
  {
    filling_material: "Gel-infused Foam",
    finish_type: "Burgundy & Cream",
    headrest: "Yes",
    max_load_capacity: 300,
    origin: "Vietnam",
  },
  {
    filling_material: "Viscose",
    finish_type: "Lavender & Charcoal",
    headrest: "No",
    max_load_capacity: 280,
    origin: "Egypt",
  },
];
